import { describe, expect, it } from "vitest";
import type { GateType, LevelDef, TargetFn } from "../types";
import { ALL_GATES, GATES } from "../engine/gates";
import { LEVELS, SANDBOX, WORLDS } from "./levels";

/* ============================================================
   Solvability solver.

   A level is "solvable" iff its target Boolean function lies in
   the clone generated by its allowed gates over the level inputs.

   - If the gate set is functionally complete (Post's criterion:
     it escapes all five maximal clones — T0, T1, monotone,
     self-dual, affine) then every target is realizable, so we
     short-circuit. This avoids enumerating the full 2^(2^n) space
     for universal palettes like {NAND} or {AND,OR,NOT}.
   - Otherwise the palette is confined to a maximal clone, whose
     closure is small, so we compute it by fixpoint and test
     membership.

   Boolean functions are encoded as a truth-table bitmask over the
   2^n input rows, with row m's input i taken from bit (n-1-i) of m
   — the same MSB-first convention the game's verifier uses.
   ============================================================ */

function projMask(i: number, n: number): number {
  let mask = 0;
  for (let m = 0; m < 1 << n; m++) if ((m >> (n - 1 - i)) & 1) mask |= 1 << m;
  return mask;
}

function targetMask(target: TargetFn, n: number): number {
  let mask = 0;
  for (let m = 0; m < 1 << n; m++) {
    const bits: boolean[] = [];
    for (let i = 0; i < n; i++) bits.push(((m >> (n - 1 - i)) & 1) === 1);
    if (target(...bits)) mask |= 1 << m;
  }
  return mask;
}

function applyUnary(fn: (a: boolean) => boolean, a: number, n: number): number {
  let r = 0;
  for (let m = 0; m < 1 << n; m++) if (fn(((a >> m) & 1) === 1)) r |= 1 << m;
  return r;
}

function applyBinary(fn: (a: boolean, b: boolean) => boolean, a: number, b: number, n: number): number {
  let r = 0;
  for (let m = 0; m < 1 << n; m++)
    if (fn(((a >> m) & 1) === 1, ((b >> m) & 1) === 1)) r |= 1 << m;
  return r;
}

/** Post-clone membership for one gate's truth table. */
function gateProps(type: GateType) {
  const def = GATES[type];
  const a = def.inputs;
  const fn = def.fn!;
  const N = 1 << a;
  const val: boolean[] = [];
  for (let m = 0; m < N; m++) {
    const xs: boolean[] = [];
    for (let j = 0; j < a; j++) xs.push(((m >> (a - 1 - j)) & 1) === 1);
    val.push(fn(...xs));
  }
  const inT0 = val[0] === false;
  const inT1 = val[N - 1] === true;

  let mono = true;
  for (let m1 = 0; m1 < N; m1++)
    for (let m2 = 0; m2 < N; m2++)
      if ((m1 & m2) === m1 && val[m1] && !val[m2]) mono = false;

  let selfDual = true;
  for (let m = 0; m < N; m++) if (val[(~m) & (N - 1)] !== !val[m]) selfDual = false;

  const c0 = val[0];
  const coeff: boolean[] = [];
  for (let j = 0; j < a; j++) coeff.push(val[1 << (a - 1 - j)] !== c0);
  let affine = true;
  for (let m = 0; m < N; m++) {
    let pred = c0;
    for (let j = 0; j < a; j++) if ((m >> (a - 1 - j)) & 1) pred = pred !== coeff[j];
    if (pred !== val[m]) affine = false;
  }
  return { inT0, inT1, mono, selfDual, affine };
}

function isComplete(palette: GateType[]): boolean {
  const p = palette.map(gateProps);
  return (
    p.some((x) => !x.inT0) &&
    p.some((x) => !x.inT1) &&
    p.some((x) => !x.mono) &&
    p.some((x) => !x.selfDual) &&
    p.some((x) => !x.affine)
  );
}

function reachableByClosure(palette: GateType[], n: number, target: number): boolean {
  const unary = palette.filter((t) => GATES[t].inputs === 1);
  const binary = palette.filter((t) => GATES[t].inputs === 2);
  const set = new Set<number>();
  for (let i = 0; i < n; i++) set.add(projMask(i, n));
  if (set.has(target)) return true;
  let changed = true;
  let guard = 0;
  while (changed && guard++ < 64) {
    changed = false;
    const cur = [...set];
    for (const a of cur) {
      for (const t of unary) {
        const r = applyUnary(GATES[t].fn!, a, n);
        if (!set.has(r)) {
          set.add(r);
          if (r === target) return true;
          changed = true;
        }
      }
      for (const b of cur) {
        for (const t of binary) {
          const r = applyBinary(GATES[t].fn!, a, b, n);
          if (!set.has(r)) {
            set.add(r);
            if (r === target) return true;
            changed = true;
          }
        }
      }
    }
    if (set.size > 70000) break; // safety net; confined clones never get here
  }
  return set.has(target);
}

function solvable(lvl: LevelDef): boolean {
  if (!lvl.target) return true;
  const n = lvl.inputs.length;
  if (isComplete(lvl.palette)) return true;
  return reachableByClosure(lvl.palette, n, targetMask(lvl.target, n));
}

/* ---- a level handle for parameterised tests ---- */
const cases = LEVELS.map((l, i) => [i + 1, l.name, l] as [number, string, LevelDef]);

describe("level dataset integrity", () => {
  it("has exactly 100 levels", () => expect(LEVELS).toHaveLength(100));

  it("has 10 worlds numbered 1..10", () => {
    expect(WORLDS.map((w) => w.id)).toEqual([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
  });

  it("each world holds exactly 10 levels", () => {
    for (const w of WORLDS) expect(LEVELS.filter((l) => l.w === w.id)).toHaveLength(10);
  });

  it.each(cases)("L%i %s is well-formed", (_i, _name, lvl) => {
    expect(lvl.name.trim().length).toBeGreaterThan(0);
    expect(lvl.goal.trim().length).toBeGreaterThan(0);
    expect(lvl.concept.trim().length).toBeGreaterThan(0);
    expect(Number.isInteger(lvl.par)).toBe(true);
    expect(lvl.par).toBeGreaterThanOrEqual(1);
    expect(lvl.inputs.length).toBeGreaterThanOrEqual(1);
    expect(lvl.inputs.length).toBeLessThanOrEqual(4);
    expect(lvl.palette.length).toBeGreaterThan(0);
    lvl.palette.forEach((t) => expect(ALL_GATES).toContain(t));
    expect(typeof lvl.target).toBe("function");
  });

  it.each(cases)("L%i %s target is total and boolean-valued", (_i, _name, lvl) => {
    const n = lvl.inputs.length;
    for (let m = 0; m < 1 << n; m++) {
      const bits: boolean[] = [];
      for (let i = 0; i < n; i++) bits.push(((m >> (n - 1 - i)) & 1) === 1);
      expect(typeof lvl.target!(...bits)).toBe("boolean");
    }
  });
});

describe("solver sanity (controls)", () => {
  const mk = (palette: GateType[], target: TargetFn): LevelDef => ({
    w: 1, name: "ctl", goal: "", par: 1, inputs: ["A", "B"], palette, concept: "", target,
  });

  it("rejects OR when only AND is allowed", () => {
    expect(solvable(mk(["AND"], (a, b) => a || b))).toBe(false);
  });

  it("rejects XOR with a monotone palette (AND, OR, no NOT)", () => {
    expect(solvable(mk(["AND", "OR"], (a, b) => a !== b))).toBe(false);
  });

  it("accepts XOR from NAND only (universal)", () => {
    expect(solvable(mk(["NAND"], (a, b) => a !== b))).toBe(true);
  });

  it("isComplete: {NAND} and {AND,OR,NOT} complete; {XOR} and {AND,OR} not", () => {
    expect(isComplete(["NAND"])).toBe(true);
    expect(isComplete(["AND", "OR", "NOT"])).toBe(true);
    expect(isComplete(["XOR"])).toBe(false);
    expect(isComplete(["AND", "OR"])).toBe(false);
  });
});

describe("every level is realizable with its allowed palette", () => {
  it.each(cases)("L%i %s is solvable", (_i, _name, lvl) => {
    expect(solvable(lvl)).toBe(true);
  });
});

describe("minGates (prove-the-identity levels)", () => {
  const byName = (name: string) => LEVELS.find((l) => l.name === name)!;

  it("flags the identity puzzles whose truth table is otherwise shortcut-able", () => {
    expect(byName("Double Negative").minGates).toBe(2); // ¬¬A = A
    expect(byName("Triple Flip").minGates).toBe(3);     // ¬¬¬A = ¬A
    expect(byName("Idempotence").minGates).toBe(1);     // A ∧ A = A
    expect(byName("Absorption").minGates).toBe(2);      // A ∨ (A ∧ B) = A
  });

  it("never demands more gates than par, and par stays achievable", () => {
    LEVELS.filter((l) => l.minGates).forEach((l) => {
      expect(l.minGates!).toBeGreaterThanOrEqual(1);
      expect(l.minGates!).toBeLessThanOrEqual(l.par);
    });
  });
});

describe("sandbox", () => {
  it("exposes all gates and has no objective", () => {
    expect(SANDBOX.palette).toEqual(ALL_GATES);
    expect(SANDBOX.target).toBeNull();
  });
});
